# https://www.appveyor.com/docs/lang/nodejs-iojs/
# https://www.appveyor.com/docs/appveyor-yml/
# https://github.com/gatsbyjs/gatsby/blob/master/appveyor.yml
platform:
  - x64

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"

# Install scripts. (runs after repo cloning)
install:
  - echo This example is built on %buildon% and the commit tag is %APPVEYOR_REPO_TAG% and the tag is %APPVEYOR_REPO_TAG_NAME%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - refreshenv
  - echo we are running on %PLATFORM%
  - node --version
  - yarn

# Post-install test scripts.
test_script:
  - yarn test

# to disable automatic builds
build: off
# to disable deployment
deploy: off
